### ISSUE TITLE
File upload broke from v0.11.0 to v0.11.1

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/magic#20]
Scott,

File upload using formData, fails starting with a127-magic v0.11.1. Version v0.11.0 works fine.

Code snippets:

swagger.yaml
```
      consumes:
        - multipart/form-data

      parameters:
        - in: formData
          name: audioFile
          description: audioFile
          required: true
          type: file
```

debug output:

```
  "message": "Request validation failed: Parameter (audioFile) is required",
  "stack": "Error: Parameter (audioFile) is required\n    at throwErrorWithCode 
  .......
  ......

```

It seems as if the actual file was missing. When the parameter is ```required```, the validator fails, when the parameter is set to optional then ```req.swagger.params.audioFile.value``` is undefined.

Any help would be greatly appreciated!

Thanks
